version: "3.9"

services:
  stackpractice:
    image: stackpractice:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=stackpractice;Username=admin;Password=admin"

  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stackpractice
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
